#!/bin/bash

simulation_id=$1
docker network rm opensand-network-${simulation_id}
docker network rm opensand-gw-network-${simulation_id}
docker network rm lan-gw1-${simulation_id}
docker network rm lan-gw2-${simulation_id}
docker network rm lan-st1-${simulation_id}
docker network rm lan-st2-${simulation_id}
docker network rm lan-st3-${simulation_id}
docker network rm lan-st4-${simulation_id}
docker network rm lan-st5-${simulation_id}
docker network create --driver=bridge --subnet=192.168.1${simulation_id}.0/24 --gateway=192.168.1${simulation_id}.1 --ipv6 --subnet=2001:660:6602:01${simulation_id}1::/64  opensand-network-${simulation_id}
docker network create --driver=bridge --subnet=192.168.2${simulation_id}.0/24 --gateway=192.168.2${simulation_id}.1 --ipv6 --subnet=2001:660:6602:01${simulation_id}2::/64 lan-gw1-${simulation_id}
docker network create --driver=bridge --subnet=192.168.3${simulation_id}.0/24 --gateway=192.168.3${simulation_id}.1 --ipv6 --subnet=2001:660:6602:01${simulation_id}3::/64 lan-gw2-${simulation_id}
docker network create --driver=bridge --subnet=192.168.4${simulation_id}.0/24 --gateway=192.168.4${simulation_id}.1  --ipv6 --subnet=2001:660:6602:01${simulation_id}4::/64 lan-st1-${simulation_id}
docker network create --driver=bridge --subnet=192.168.5${simulation_id}.0/24 --gateway=192.168.5${simulation_id}.1  --ipv6 --subnet=2001:660:6602:01${simulation_id}5::/64 lan-st2-${simulation_id}
docker network create --driver=bridge --subnet=192.168.6${simulation_id}.0/24 --gateway=192.168.6${simulation_id}.1  --ipv6 --subnet=2001:660:6602:01${simulation_id}6::/64 lan-st3-${simulation_id}
docker network create --driver=bridge --subnet=192.168.7${simulation_id}.0/24 --gateway=192.168.7${simulation_id}.1  --ipv6 --subnet=2001:660:6602:01${simulation_id}7::/64 lan-st4-${simulation_id}
docker network create --driver=bridge --subnet=192.168.8${simulation_id}.0/24 --gateway=192.168.8${simulation_id}.1  --ipv6 --subnet=2001:660:6602:01${simulation_id}8::/64 lan-st5-${simulation_id}
docker network create --driver=bridge --subnet=192.168.9${simulation_id}.0/24 opensand-gw-network-${simulation_id}
 
